### ISSUE TITLE
No blocked call hang up if BLOCKED_ACTIONS = ()

### ISSUE THREAD

**Issue by drano02** [emxsys/callattendant#126]
If BLOCKED_ACTIONS = () and a blocked caller calls, it will not answer and hang up on the caller. The phone keeps on ringing. I had the same problem with v1.0. In app.py, if I change the following to not check the length of actions, it works for me:

                # Answer the call!
**#               if ok_to_answer and len(actions) > 0:
                if ok_to_answer:**
                    self.answer_call(actions, greeting, call_no, caller)

**Comment by emxsys** [comment]
@drano02 Thanks for reporting this. I will investigate.
