### ISSUE TITLE
Embellish Call Log web interface

### ISSUE THREAD

**Issue by emxsys** [emxsys/callattendant#13]
- [x] Highlight whitelisted and blacklisted callers
- [x] Periodically refresh page 
- [x] Add action taken
- [x] Add capability to add caller to whitelist or blacklist
- [x] Add navigation links between the call log, whitelist and blacklist pages.

**Comment by emxsys** [comment]
@zomGreg I'm going to try and wrap up the nav links and the basic "add to" blacklist/whitelist today.  Then release 0.2 will be complete.

**Comment by zomGreg** [comment]
I've got nav links in https://github.com/zomGreg/callattendant/tree/frontend_testing if you want to see what I was doing. I'm no frontend wizard, so what you have will probably be better than that.

**Comment by emxsys** [comment]
@zomGreg Excellent. I was going down the same path, but you're a step ahead of me.  I'd like take your changes in PR, please.

**Comment by zomGreg** [comment]
okay, I'll pop them in.

**Comment by emxsys** [comment]
@zomGreg The nav links work good. Thanks!  I'm embellishing the aesthetics and will check in the changes later today.

**Comment by emxsys** [comment]
@zomGreg FYI: I found the changes made to `callattendant.css` are not realized until you clear your browser's cache/history.

**Comment by emxsys** [comment]
The call log enhancements are complete for version 0.2.
