### ISSUE TITLE
Port to Python3.x

### ISSUE THREAD

**Issue by zomGreg** [emxsys/callattendant#36]
Should port this to the/a current version of Python. >= 3.6

**Comment by emxsys** [comment]
@zomGreg I see you've already started on this issue. :1st_place_medal:   I'll add it to milestone 0.3 and try to leave the master branch intact. In the meantime I'll be working on the messaging features in a separate branch.

**Comment by emxsys** [comment]
It should be noted (in the README) that on the Raspberry Pi, when running Python3 outside of a virtual environment, you need to use the `python3` and `pip3` commands (instead of `python` and  `pip`), e.g.,
```
pip3 install -r requirements.txt

python3 callattendant.py -c app.cfg
```
